spring.application.name=user-service
server.port=9030


spring.mongodb.uri=mongodb://springuser:password123@localhost:27017/UserDB?authSource=admin
spring.mongodb.database=UserDB
spring.data.mongodb.auto-index-creation=true
