spring.application.name=user-service
server.port=9030


spring.mongodb.uri=mongodb://springuser:password123@localhost:27017/UserDB?authSource=admin
spring.mongodb.database=UserDB
spring.data.mongodb.auto-index-creation=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=health,info

jwt.access-token-expiration=900000
jwt.access-token-secret=${JWT_ACCESS_TOKEN_SECRET}
